import { readFileSync } from 'node:fs'
import * as esbuild from 'esbuild'

await esbuild.build({
	entryPoints: ['src/server.ts'],
	bundle: true,
	platform: 'node',
	format: 'esm',
	target: 'node22',
	outfile: 'api/index.js',
	legalComments: 'none',
	banner: { js: '/* Generated by npm run build. Do not edit. */' },
})

const bundled = readFileSync('api/index.js', 'utf8')
if (/from\s+['"][^'"]+\.ts['"]|import\s*\(\s*['"][^'"]+\.ts['"]/.test(bundled)) {
	throw new Error('Vercel bundle still imports a .ts module')
}
