/* Generated by npm run build. Do not edit. */

// src/providers/baidu.ts
async function baidu(q, lang) {
  const url = `https://www.baidu.com/sugrec?prod=pc&wd=${encodeURIComponent(q)}`;
  const json = await fetchProviderJson(url, lang);
  if (!json?.g) {
    return [];
  }
  return json.g.flatMap((item) => item.q ? [{ text: item.q }] : []);
}

// src/providers/bing.ts
async function bing(q, lang) {
  const market = !lang ? "" : lang.includes("-") ? lang : lang + "-" + lang;
  const url = `https://www.bing.com/AS/Suggestions?qry=${encodeURIComponent(q)}&mkt=${encodeURIComponent(market)}&cp=5&csr=1&msbqf=false&cvid=7AE3B40123C74FFF87EF8A5ED4FAF455`;
  const json = await fetchProviderJson(url, lang);
  const result = [];
  if (!json) {
    return [];
  }
  for (const item of Object.values(json.s)) {
    result.push({
      text: item.q.replace("\uE000", "").replace("\uE001", ""),
      desc: item.ext ? item.ext?.des : void 0,
      image: item.ext ? "https://th.bing.com" + item.ext?.im : void 0
    });
  }
  return result;
}

// src/providers/duckduckgo.ts
async function duckduckgo(q, lang) {
  const region = lang === "zh-CN" ? "cn-zh" : lang;
  const url = `https://duckduckgo.com/ac/?q=${encodeURIComponent(q)}&kl=${encodeURIComponent(region)}`;
  const json = await fetchProviderJson(url, lang);
  if (json) {
    return Object.values(json).map((item) => ({ text: item.phrase }));
  }
  return [];
}

// src/providers/google.ts
async function google(q, lang) {
  const hl = encodeURIComponent(lang);
  const gl = lang === "zh-CN" ? "&gl=cn" : "";
  const url = `https://www.google.com/complete/search?q=${encodeURIComponent(q)}&hl=${hl}&client=gws-wiz${gl}`;
  let text = await fetchProviderText(url, lang) ?? "";
  try {
    text = text.replace("window.google.ac.h(", "");
    text = text.slice(0, text.length - 1);
    const json = JSON.parse(text);
    if (json) {
      return json[0].map((item) => {
        const wordDefinition = item[3]?.ansa?.l[1]?.il?.t[0]?.t;
        const text2 = item[0].replaceAll("<b>", "").replaceAll("</b>", "").replaceAll("&#39;", "'");
        const desc = (wordDefinition ?? item[3]?.zi ?? "").replaceAll("&#39;", "'");
        const image = item[3]?.zs;
        return { text: text2, image, desc };
      });
    }
  } catch (_) {
    console.warn("Failed while parsing Google response");
  }
  return [];
}

// src/locales.ts
var SIMPLIFIED_CHINESE = /* @__PURE__ */ new Set(["zh", "zh-cn", "zh-hans", "zh-hans-cn"]);
function normalizeLang(lang) {
  const key = lang.trim().toLowerCase().replaceAll("_", "-");
  if (SIMPLIFIED_CHINESE.has(key)) {
    return "zh-CN";
  }
  return lang.trim();
}

// src/index.ts
var USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/114.0";
function providerHeaders(lang = "") {
  const acceptLanguage = lang === "zh-CN" ? "zh-CN,zh;q=0.9" : lang ? `${lang};q=0.9` : "en-US,en;q=1";
  return {
    "Accept-Language": acceptLanguage,
    "User-Agent": USER_AGENT
  };
}
async function handler(args = { q: "", with: "", lang: "" }) {
  const { q } = args;
  const lang = normalizeLang(args.lang ?? "");
  if (!q) {
    return [];
  }
  switch (args.with) {
    case "ddg":
    case "duckduckgo":
      return await duckduckgo(q, lang);
    case "google":
      return await google(q, lang);
    case "bing":
      return await bing(q, lang);
    case "baidu":
      return await baidu(q, lang);
    default:
      return [];
  }
}
async function fetchProviderJson(url, lang = "") {
  try {
    const response = await fetch(url, { headers: providerHeaders(lang) });
    try {
      return await response.json();
    } catch (_) {
      console.warn(`Cannot parse ${url} as JSON`);
    }
  } catch (_) {
    console.warn(`Cannot reach ${url}`);
  }
}
async function fetchProviderText(url, lang = "") {
  try {
    const response = await fetch(url, { headers: providerHeaders(lang) });
    try {
      return await response.text();
    } catch (_) {
      console.warn(`Cannot get ${url} as text`);
    }
  } catch (_) {
    console.warn(`Cannot reach ${url}`);
  }
}

// src/http.ts
async function responseAsHttp(request) {
  const url = new URL(request.url);
  const params = new URLSearchParams(url.searchParams);
  const result = await handler({
    q: params.get("q") ?? "",
    lang: params.get("l") ?? "en",
    with: params.get("with") ?? "duckduckgo"
  });
  return new Response(JSON.stringify(result), {
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*"
    }
  });
}

// src/server.ts
var cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type"
};
var server_default = {
  async fetch(request) {
    if (request.headers.get("Upgrade") === "websocket") {
      return Response.json(
        { error: "WebSocket suggestions are served by the Cloudflare deployment" },
        { status: 501, headers: cors }
      );
    }
    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: cors });
    }
    if (request.method !== "GET") {
      return new Response("", { status: 405, headers: cors });
    }
    return responseAsHttp(request);
  }
};
export {
  server_default as default
};
